In [5]:
import numpy as np
my_list = [34 , 343 ,43]
my_li = np.array(my_list)
my_li

array([ 34, 343,  43])

In [4]:
np.array([34 ,3434 ,3434])

array([  34, 3434, 3434])

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.linspace(0 , 100 , 20)

array([   0.        ,    5.26315789,   10.52631579,   15.78947368,
         21.05263158,   26.31578947,   31.57894737,   36.84210526,
         42.10526316,   47.36842105,   52.63157895,   57.89473684,
         63.15789474,   68.42105263,   73.68421053,   78.94736842,
         84.21052632,   89.47368421,   94.73684211,  100.        ])

In [25]:
arr = np.arange(0 , 1000 , 25)
arr
arr = np.random.randint(0 , 1000 , 25)
arr

array([318, 933, 872, 352, 397, 348, 717, 427, 806, 160, 713, 122, 633,
       847, 436, 643, 938, 765, 931, 318, 858, 782, 123, 625, 613])

In [26]:
arr.reshape(5 , 5)

array([[318, 933, 872, 352, 397],
       [348, 717, 427, 806, 160],
       [713, 122, 633, 847, 436],
       [643, 938, 765, 931, 318],
       [858, 782, 123, 625, 613]])

In [32]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [33]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [34]:
np.eye((5, 6))

TypeError: an integer is required

In [35]:
np.eye(4,5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [36]:
np.array(4.5)

array(4.5)

In [37]:
np.array([445, 53 ,344])

array([445,  53, 344])

In [38]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [39]:
np.ones(10)


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [40]:
np.ones(10) * 5


array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [41]:
np.arange(0 , 10 , 5)

array([0, 5])

In [42]:
np.linspace(0 , 101 , 5)

array([   0.  ,   25.25,   50.5 ,   75.75,  101.  ])

In [43]:
np.arange(10 , 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [44]:
np.arange(0 , 9).reshape(3 , 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
np.eye(3 , 3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [47]:
np.random.randn(25)

array([ 0.94321256, -1.12601094, -1.19420676, -0.81333775, -0.29756411,
       -0.96492095, -0.56193149, -1.19461942,  1.29198454, -0.12235685,
       -0.16728975, -0.5882029 ,  1.93370233,  0.34322126, -0.23067559,
       -0.21405056, -1.68155427,  0.16400915, -0.46693299,  0.48259004,
        0.71436267, -0.51319728,  0.82008073,  0.17265942,  0.55412433])

In [48]:
np.random.rand(10 , 50)

array([[ 0.46518044,  0.25295477,  0.48272602,  0.54874816,  0.34230293,
         0.95347647,  0.90384293,  0.75846051,  0.99327198,  0.83710364,
         0.89094708,  0.50943987,  0.11491843,  0.2875707 ,  0.81005067,
         0.52660617,  0.95038004,  0.14759148,  0.55275092,  0.36415759,
         0.47243698,  0.05506344,  0.83299026,  0.56738383,  0.32482927,
         0.62800853,  0.97923866,  0.39041373,  0.97835814,  0.9574942 ,
         0.51696483,  0.79744444,  0.82245784,  0.63824922,  0.83332971,
         0.59477275,  0.93666189,  0.53944573,  0.4283601 ,  0.06127107,
         0.90540495,  0.61225086,  0.37025148,  0.59031501,  0.79118006,
         0.64467888,  0.43504474,  0.65064275,  0.55644906,  0.09705024],
       [ 0.49643326,  0.07797424,  0.67123038,  0.49826927,  0.20264035,
         0.1108981 ,  0.12405748,  0.20519713,  0.43336496,  0.41018436,
         0.72121158,  0.94055517,  0.22888371,  0.56307714,  0.0293559 ,
         0.91229395,  0.29305193,  0.06145575,  0.

In [49]:
np.linspace(0 , 1 , 20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [71]:
np.arange(0 , 1 , 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [68]:
np.arange(0.01 , 1.01 , 0.01).reshape(10 , 10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [69]:
np.linspace(0.1 , 1.1 )

array([ 0.1       ,  0.12040816,  0.14081633,  0.16122449,  0.18163265,
        0.20204082,  0.22244898,  0.24285714,  0.26326531,  0.28367347,
        0.30408163,  0.3244898 ,  0.34489796,  0.36530612,  0.38571429,
        0.40612245,  0.42653061,  0.44693878,  0.46734694,  0.4877551 ,
        0.50816327,  0.52857143,  0.54897959,  0.56938776,  0.58979592,
        0.61020408,  0.63061224,  0.65102041,  0.67142857,  0.69183673,
        0.7122449 ,  0.73265306,  0.75306122,  0.77346939,  0.79387755,
        0.81428571,  0.83469388,  0.85510204,  0.8755102 ,  0.89591837,
        0.91632653,  0.93673469,  0.95714286,  0.97755102,  0.99795918,
        1.01836735,  1.03877551,  1.05918367,  1.07959184,  1.1       ])

In [70]:
np.arange(0 , 1.01 , 0.01)

array([ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
        0.09,  0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,
        0.18,  0.19,  0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,
        0.27,  0.28,  0.29,  0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,
        0.36,  0.37,  0.38,  0.39,  0.4 ,  0.41,  0.42,  0.43,  0.44,
        0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ,  0.51,  0.52,  0.53,
        0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ,  0.61,  0.62,
        0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ,  0.71,
        0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ,
        0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,
        0.9 ,  0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,
        0.99,  1.  ])

In [4]:
from sklearn.family import Model

ModuleNotFoundError: No module named 'sklearn.family'

In [6]:
from sklearn.linear_model import LinearRegression